export const currencies = [
  { name: "US Dollar", code: "usd", symbol: "$" },
  { name: "Euro", code: "eur", symbol: "€" },
  { name: "British Pound", code: "gbp", symbol: "£" },
  { name: "Australian Dollar", code: "aud", symbol: "A$" },
  { name: "Brazilian Real", code: "brl", symbol: "R$" },
  { name: "Canadian Dollar", code: "cad", symbol: "C$" },
  { name: "Swiss Franc", code: "chf", symbol: "CHF" },
  { name: "Chinese Yuan", code: "cny", symbol: "¥" },
  { name: "Hong Kong Dollar", code: "hkd", symbol: "HK$" },
  { name: "Indian Rupee", code: "inr", symbol: "₹" },
  { name: "Japanese Yen", code: "jpy", symbol: "¥" },
  { name: "Mexican Peso", code: "mxn", symbol: "Mex$" },
  { name: "New Zealand Dollar", code: "nzd", symbol: "NZ$" },
  { name: "Singapore Dollar", code: "sgd", symbol: "S$" },
];
